version: '3.3'

services:
  mysql:
    image: mysql:5.5
    container_name: acis_database
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3333:3306" # 1° porta externa | 2° porta interna container
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - l2network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  mysql_data:

networks:
  l2network:
    driver: bridge
